### ISSUE TITLE
Undetermined package incompatibility leading to downgrade to 1.7.1

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pytorch-cpu-feedstock#100]
Seeing this in https://github.com/conda-forge/allennlp-feedstock/pull/37

```
    import torch.fx
ModuleNotFoundError: No module named 'torch.fx'
```

Concerningly, going up the call stack shows that this comes just from `import torchvision`:
```
+ allennlp checklist --help
Traceback (most recent call last):
  File "[...]/bin/allennlp", line 11, in <module>
    sys.exit(run())
  File "[...]/lib/python3.8/site-packages/allennlp/__main__.py", line 33, in run
    from allennlp.commands import main  # noqa
  File "[...]/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.build_vocab import BuildVocab
  File "[...]/lib/python3.8/site-packages/allennlp/commands/build_vocab.py", line 16, in <module>
    from allennlp.training.util import make_vocab_from_params
  File "[...]/lib/python3.8/site-packages/allennlp/training/__init__.py", line 2, in <module>
    from allennlp.training.no_op_trainer import NoOpTrainer
  File "[...]/lib/python3.8/site-packages/allennlp/training/no_op_trainer.py", line 6, in <module>
    from allennlp.models import Model
  File "[...]/lib/python3.8/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.model import Model
  File "[...]/lib/python3.8/site-packages/allennlp/models/model.py", line 18, in <module>
    from allennlp.data import Instance, Vocabulary
  File "[...]/lib/python3.8/site-packages/allennlp/data/__init__.py", line 15, in <module>
    from allennlp.data.image_loader import ImageLoader, TorchImageLoader
  File "[...]/lib/python3.8/site-packages/allennlp/data/image_loader.py", line 6, in <module>
    import torchvision
  File "[...]/lib/python3.8/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import models
  File "[...]/lib/python3.8/site-packages/torchvision/models/__init__.py", line 8, in <module>
    from .mobilenet import *
  File "[...]/lib/python3.8/site-packages/torchvision/models/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import MobileNetV2, mobilenet_v2, __all__ as mv2_all
  File "[...]/lib/python3.8/site-packages/torchvision/models/mobilenetv2.py", line 8, in <module>
    from ..ops.misc import ConvNormActivation
  File "[...]/lib/python3.8/site-packages/torchvision/ops/__init__.py", line 12, in <module>
    from .stochastic_depth import stochastic_depth, StochasticDepth
  File "[...]/lib/python3.8/site-packages/torchvision/ops/stochastic_depth.py", line 2, in <module>
    import torch.fx
ModuleNotFoundError: No module named 'torch.fx'
```

**Comment by h-vetinari** [comment]
Hm, this is quite strange to me now. In https://github.com/conda-forge/torchvision-feedstock/pull/54, `import torchvision` succeeds.

CC @conda-forge/torchvision - any idea what's going on here?

**Comment by h-vetinari** [comment]
OK, I thought I had checked this correctly but must have confused myself. For some reason, the affected builds pull in:
```
pytorch:                       1.7.1-cpu_py38h36eccb8_2     conda-forge
```

but only on python 3.8 & 3.9, not 3.7.

**Comment by h-vetinari** [comment]
Should be fixed by https://github.com/conda-forge/admin-requests/pull/427

**Comment by h-vetinari** [comment]
Should have been fixed by https://github.com/conda-forge/admin-requests/pull/427 now
