### ISSUE TITLE
Rerendering locally with conda-smithy fails

### ISSUE THREAD

**Issue by jjerphan** [conda-forge/pytorch-cpu-feedstock#217]
As of 99445d4755b74a37a1b2333a2c809431baaca3c2, re-rendering locally using `conda-smithy==3.30.4` fails:

<details>

<summary>Full log</summary>

```
INFO:conda_smithy.configure_feedstock:README rendering is skipped
INFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped
INFO:conda_smithy.configure_feedstock:cuda118.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:libabseil20230802_libgrpc157_libprotobuf4234.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:libgrpc159_libprotobuf4244.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:python312.yaml from feedstock is ignored and upstream version is used
WARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from /home/jjerphan/.cache/conda-smithy/conda_build_config.yaml
Adding in variants from /home/jjerphan/dev/pytorch-cpu-feedstock/recipe/conda_build_config.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /home/jjerphan/dev/pytorch-cpu-feedstock/.ci_support/migrations/cuda120.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libabseil20230802_libgrpc157_libprotobuf4234.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/cuda118.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/python312.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libgrpc159_libprotobuf4244.yaml
Adding in variants from argument_variants
INFO:conda_smithy.configure_feedstock:Applying migrations: /home/jjerphan/dev/pytorch-cpu-feedstock/.ci_support/migrations/cuda120.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libabseil20230802_libgrpc157_libprotobuf4234.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/cuda118.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/python312.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libgrpc159_libprotobuf4244.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /home/jjerphan/dev/pytorch-cpu-feedstock/.ci_support/migrations/cuda120.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libabseil20230802_libgrpc157_libprotobuf4234.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/cuda118.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/python312.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libgrpc159_libprotobuf4244.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /home/jjerphan/dev/pytorch-cpu-feedstock/.ci_support/migrations/cuda120.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libabseil20230802_libgrpc157_libprotobuf4234.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/cuda118.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/python312.yaml,/home/jjerphan/.cache/conda-smithy/share/conda-forge/migrations/libgrpc159_libprotobuf4244.yaml
Traceback (most recent call last):
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/cli.py", line 724, in main
    args.subcommand_func(args)
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/cli.py", line 584, in __call__
    self._call(args, tmpdir)
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/cli.py", line 589, in _call
    configure_feedstock.main(
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 2564, in main
    render_github_actions(env, config, forge_dir, return_metadata=True)
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 1403, in render_github_actions
    return _render_ci_provider(
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 688, in _render_ci_provider
    migrated_combined_variant_spec = migrate_combined_spec(
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 621, in migrate_combined_spec
    combined_spec = variant_add(combined_spec, migration)
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/variant_algebra.py", line 290, in variant_add
    return VARIANT_OP[operation](v1, v2)
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/variant_algebra.py", line 177, in op_variant_key_add
    new_keys = variant_key_set_union(
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/variant_algebra.py", line 115, in variant_key_set_union
    return sorted(out_v, key=partial(_version_order, ordering=ordering))
  File "/home/jjerphan/.local/share/miniforge3/envs/pytorch/lib/python3.9/site-packages/conda_smithy/variant_algebra.py", line 66, in _version_order
    return ordering.index(v)
ValueError: '11.8' is not in list
```

</details>

Yet, I have been able to re-render with the following naive changes to conda smithy as of https://github.com/conda-forge/conda-smithy/commit/a8d97615481230ff3aa87bab8a92d0e2c98f1ec6 to work around the observed error:

<details>

<summary>Work around for <code>conda-smithy</code></summary>

```diff
diff --git a/conda_smithy/variant_algebra.py b/conda_smithy/variant_algebra.py
index 3273f13..69e312d 100644
--- a/conda_smithy/variant_algebra.py
+++ b/conda_smithy/variant_algebra.py
@@ -62,6 +62,18 @@ def parse_variant(
 def _version_order(
     v: Union[str, float], ordering: Optional[List[str]] = None
 ) -> Union[int, VersionOrder, float]:
+    # XXX: 11.8 for condatoolkit is not being added to `ordering`,
+    # eventhough it is listed in the specification.
+    if (
+        ordering == ['None', '10.2', '11.0', '11.1', '11.2', '12.0']
+    ):
+        print("Added 11.8 to ordering")
+        ordering = ['None', '10.2', '11.0', '11.1', '11.2', '11.8', '12.0']
+    if (
+        ordering == ['None', '11.2', '12.0']
+    ):
+        print("Added 11.8 to ordering")
+        ordering = ['None', '11.2', '11.8', '12.0']
     if ordering is not None:
         return ordering.index(v)
     else:
```

For convenient to skip version verification which is 0.0.0 when built from sources:

```diff 
diff --git a/conda_smithy/configure_feedstock.py b/conda_smithy/configure_feedstock.py
index 91068f3..ffc559e 100644
--- a/conda_smithy/configure_feedstock.py
+++ b/conda_smithy/configure_feedstock.py
@@ -2205,21 +2205,7 @@ def get_most_recent_version(name):
 
 
 def check_version_uptodate(name, installed_version, error_on_warn):
-    from conda_build.conda_interface import VersionOrder
-
-    most_recent_version = get_most_recent_version(name).version
-    if installed_version is None:
-        msg = "{} is not installed in conda-smithy's environment.".format(name)
-    elif VersionOrder(installed_version) < VersionOrder(most_recent_version):
-        msg = "{} version ({}) is out-of-date ({}) in conda-smithy's environment.".format(
-            name, installed_version, most_recent_version
-        )
-    else:
-        return
-    if error_on_warn:
-        raise RuntimeError("{} Exiting.".format(msg))
-    else:
-        logger.info(msg)
+    pass
 
 
 def commit_changes(forge_file_directory, commit, cs_ver, cfp_ver, cb_ver):
```

</details>

This produces the following changes, but I am unsure about their validity:

<details>

<summary>Result of rerendering</summary>

```diff
commit 681f737cdd81b4a0571a8cd6ad53c35244069323
Author: Julien Jerphanion <git@jjerphan.xyz>
Date:   Fri Jan 26 16:17:52 2024 +0100

    MNT: Re-rendered with conda-build 3.28.4, conda-smithy 0.0.0, and conda-forge-pinning 2024.01.26.12.19.12

diff --git a/.ci_support/linux_64_blas_implgenericc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml b/.ci_support/linux_64_blas_implgenericc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
index 422cfca..cc0deda 100644
--- a/.ci_support/linux_64_blas_implgenericc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
+++ b/.ci_support/linux_64_blas_implgenericc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml b/.ci_support/linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
index 275ca69..59c8f10 100644
--- a/.ci_support/linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
+++ b/.ci_support/linux_64_blas_implgenericc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml b/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
index 6b1bbdb..f9333cf 100644
--- a/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
+++ b/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml b/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml
index fb0eb66..658ccea 100644
--- a/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml
+++ b/.ci_support/linux_64_blas_implgenericc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implmklc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml b/.ci_support/linux_64_blas_implmklc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
index b880b6a..7bc53cf 100644
--- a/.ci_support/linux_64_blas_implmklc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
+++ b/.ci_support/linux_64_blas_implmklc_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implmklc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml b/.ci_support/linux_64_blas_implmklc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
index 1af79a1..2d1e826 100644
--- a/.ci_support/linux_64_blas_implmklc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
+++ b/.ci_support/linux_64_blas_implmklc_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml b/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
index fcbd570..8ccdb5e 100644
--- a/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
+++ b/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml b/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml
index 81c6629..ecb96b7 100644
--- a/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml
+++ b/.ci_support/linux_64_blas_implmklc_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-64
 zip_keys:
diff --git a/.ci_support/linux_aarch64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml b/.ci_support/linux_aarch64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
index 01a7fc8..cb1a16a 100644
--- a/.ci_support/linux_aarch64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
+++ b/.ci_support/linux_aarch64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
@@ -53,7 +53,7 @@ python:
 - 3.8.* *_cpython
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - linux-aarch64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implgenericnumpy1.22python3.10.____cpython.yaml b/.ci_support/osx_64_blas_implgenericnumpy1.22python3.10.____cpython.yaml
index 5ce1032..2978c14 100644
--- a/.ci_support/osx_64_blas_implgenericnumpy1.22python3.10.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implgenericnumpy1.22python3.10.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.10.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implgenericnumpy1.22python3.8.____cpython.yaml b/.ci_support/osx_64_blas_implgenericnumpy1.22python3.8.____cpython.yaml
index 30b969c..8771535 100644
--- a/.ci_support/osx_64_blas_implgenericnumpy1.22python3.8.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implgenericnumpy1.22python3.8.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.8.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implgenericnumpy1.22python3.9.____cpython.yaml b/.ci_support/osx_64_blas_implgenericnumpy1.22python3.9.____cpython.yaml
index 6e0a210..b6011a2 100644
--- a/.ci_support/osx_64_blas_implgenericnumpy1.22python3.9.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implgenericnumpy1.22python3.9.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implgenericnumpy1.23python3.11.____cpython.yaml b/.ci_support/osx_64_blas_implgenericnumpy1.23python3.11.____cpython.yaml
index 820ec68..2c24668 100644
--- a/.ci_support/osx_64_blas_implgenericnumpy1.23python3.11.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implgenericnumpy1.23python3.11.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.11.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implgenericnumpy1.26python3.12.____cpython.yaml b/.ci_support/osx_64_blas_implgenericnumpy1.26python3.12.____cpython.yaml
index 4cda12b..1b9e625 100644
--- a/.ci_support/osx_64_blas_implgenericnumpy1.26python3.12.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implgenericnumpy1.26python3.12.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.12.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implmklnumpy1.22python3.10.____cpython.yaml b/.ci_support/osx_64_blas_implmklnumpy1.22python3.10.____cpython.yaml
index 3a53c6e..e822315 100644
--- a/.ci_support/osx_64_blas_implmklnumpy1.22python3.10.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implmklnumpy1.22python3.10.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.10.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implmklnumpy1.22python3.8.____cpython.yaml b/.ci_support/osx_64_blas_implmklnumpy1.22python3.8.____cpython.yaml
index 23390a1..c9948a8 100644
--- a/.ci_support/osx_64_blas_implmklnumpy1.22python3.8.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implmklnumpy1.22python3.8.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.8.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implmklnumpy1.22python3.9.____cpython.yaml b/.ci_support/osx_64_blas_implmklnumpy1.22python3.9.____cpython.yaml
index 1ec3aa4..8e57437 100644
--- a/.ci_support/osx_64_blas_implmklnumpy1.22python3.9.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implmklnumpy1.22python3.9.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implmklnumpy1.23python3.11.____cpython.yaml b/.ci_support/osx_64_blas_implmklnumpy1.23python3.11.____cpython.yaml
index f56d6b9..5bd7bdd 100644
--- a/.ci_support/osx_64_blas_implmklnumpy1.23python3.11.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implmklnumpy1.23python3.11.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.11.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_64_blas_implmklnumpy1.26python3.12.____cpython.yaml b/.ci_support/osx_64_blas_implmklnumpy1.26python3.12.____cpython.yaml
index f7688b2..223142e 100644
--- a/.ci_support/osx_64_blas_implmklnumpy1.26python3.12.____cpython.yaml
+++ b/.ci_support/osx_64_blas_implmklnumpy1.26python3.12.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.12.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-64
 zip_keys:
diff --git a/.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml b/.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
index 8e4ec93..59de737 100644
--- a/.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
+++ b/.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.10.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-arm64
 zip_keys:
diff --git a/.ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml b/.ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml
index f0fbcc9..84b0ff4 100644
--- a/.ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml
+++ b/.ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.8.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-arm64
 zip_keys:
diff --git a/.ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml b/.ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml
index a147fb4..e39f354 100644
--- a/.ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml
+++ b/.ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.9.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-arm64
 zip_keys:
diff --git a/.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml b/.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
index b35ff54..71c0a57 100644
--- a/.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
+++ b/.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.11.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-arm64
 zip_keys:
diff --git a/.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml b/.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
index 850e734..9b20761 100644
--- a/.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
+++ b/.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
@@ -45,7 +45,7 @@ pin_run_as_build:
 python:
 - 3.12.* *_cpython
 pytorch:
-- '2.0'
+- '2.1'
 target_platform:
 - osx-arm64
 zip_keys:
diff --git a/.gitignore b/.gitignore
index c002910..179afe5 100644
--- a/.gitignore
+++ b/.gitignore
@@ -3,11 +3,22 @@
 # Everything else is managed by the conda-smithy rerender process.
 # Please do not modify
 
+# Ignore all files and folders in root
 *
 !/conda-forge.yml
 
-!/*/
+# Don't ignore any files/folders if the parent folder is 'un-ignored'
+# This also avoids warnings when adding an already-checked file with an ignored parent.
+!/**/
+# Don't ignore any files/folders recursively in the following folders
 !/recipe/**
 !/.ci_support/**
 
+# Since we ignore files/folders recursively, any folders inside
+# build_artifacts gets ignored which trips some build systems.
+# To avoid that we 'un-ignore' all files/folders recursively
+# and only ignore the root build_artifacts folder.
+!/build_artifacts/**
+/build_artifacts
+
 *.pyc
diff --git a/.scripts/build_steps.sh b/.scripts/build_steps.sh
index 657b2cd..6c18885 100755
--- a/.scripts/build_steps.sh
+++ b/.scripts/build_steps.sh
@@ -57,12 +57,6 @@ if [[ -f "${FEEDSTOCK_ROOT}/LICENSE.txt" ]]; then
   cp "${FEEDSTOCK_ROOT}/LICENSE.txt" "${RECIPE_ROOT}/recipe-scripts-license.txt"
 fi
 
-if [[ "${sha:-}" == "" ]]; then
-  pushd ${FEEDSTOCK_ROOT}
-  sha=$(git rev-parse HEAD)
-  popd
-fi
-
 if [[ "${BUILD_WITH_CONDA_DEBUG:-0}" == 1 ]]; then
     if [[ "x${BUILD_OUTPUT_ID:-}" != "x" ]]; then
         EXTRA_CB_OPTIONS="${EXTRA_CB_OPTIONS:-} --output-id ${BUILD_OUTPUT_ID}"
diff --git a/.scripts/run_docker_build.sh b/.scripts/run_docker_build.sh
index b70ef01..00f377a 100755
--- a/.scripts/run_docker_build.sh
+++ b/.scripts/run_docker_build.sh
@@ -21,6 +21,12 @@ if [ -z ${FEEDSTOCK_NAME} ]; then
     export FEEDSTOCK_NAME=$(basename ${FEEDSTOCK_ROOT})
 fi
 
+if [[ "${sha:-}" == "" ]]; then
+  pushd "${FEEDSTOCK_ROOT}"
+  sha=$(git rev-parse HEAD)
+  popd
+fi
+
 docker info
 
 # In order for the conda-build process in the container to write to the mounted
diff --git a/build-locally.py b/build-locally.py
index 3f4b7a7..e0d408d 100755
--- a/build-locally.py
+++ b/build-locally.py
@@ -64,8 +64,9 @@ def verify_config(ns):
     elif ns.config.startswith("osx"):
         if "OSX_SDK_DIR" not in os.environ:
             raise RuntimeError(
-                "Need OSX_SDK_DIR env variable set. Run 'export OSX_SDK_DIR=SDKs' "
-                "to download the SDK automatically to 'SDKs/MacOSX<ver>.sdk'. "
+                "Need OSX_SDK_DIR env variable set. Run 'export OSX_SDK_DIR=$PWD/SDKs' "
+                "to download the SDK automatically to '$PWD/SDKs/MacOSX<ver>.sdk'. "
+                "Note: OSX_SDK_DIR must be set to an absolute path. "
                 "Setting this variable implies agreement to the licensing terms of the SDK by Apple."
             )
 
```

</details>

I do not know whether this is an issue with conda-smithy or this feedstock yet.

**Comment by jaimergp** [comment]
@conda-forge/conda-smithy ?

**Comment by isuruf** [comment]
You need to add a 11.8 at https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/.ci_support/migrations/cuda120.yaml#L53-L54

This is why I was skeptical of updating the migration_number https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5121 and preferred a new migrator. cc @jakirkham

**Comment by jakirkham** [comment]
> You need to add a 11.8 at https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/.ci_support/migrations/cuda120.yaml#L53-L54
> 
> This is why I was skeptical of updating the migration_number [conda-forge/conda-forge-pinning-feedstock#5121](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5121) and preferred a new migrator. cc @jakirkham

Not sure that link was intended (if it was I'm not following). Think you are referring to PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5340 ) where the 11.8 was added to the CUDA 12 migrator

Generally conda-smithy does the right thing as pointed out by Axel and later confirmed by me in this thread ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5340#discussion_r1441268175 )

There are two cases we have seen where re-rendering out of the box doesn't work:

1. The `use_local` case (as discussed in that thread)
2. conda-smithy migrator cache goes stale and doesn't refresh it ( https://github.com/conda-forge/conda-smithy/issues/1833 )

For 1, I sent a bunch of PRs xref'd at the bottom that manually fix those feedstocks. Nearly all are merged. The 2 remaining we could merge if we like. Have left that task to maintainers for now

2 is what Julien ran into. All that is needed is to purge conda-smithy's stale migrator cache so it refreshes. In cases where there is no cache (like the bot) this issue doesn't occur

On my system purging conda-smithy's migrator cache looks like this

```
rm -rf ~/.cache/conda-smithy/share/conda-forge/migrations
```

Ideally conda-smithy could detect if the cache is stale and do this for us
