### ISSUE TITLE
Missing `typing_extensions` dependency

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/pytorch-cpu-feedstock#29]
It seems `typing_extensions` is required:
https://github.com/pytorch/pytorch/blob/a5339b9d7cb52588b608d2d4ae61a3b571eb3b35/setup.py#L354-L358

**Comment by dhirschfeld** [comment]
This came up in a [`staged-recipes` PR](https://github.com/conda-forge/staged-recipes/pull/12839):
```
import: 'torchsde'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/test_tmp/run_test.py", line 2, in <module>
    import torchsde
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torchsde/__init__.py", line 15, in <module>
    from ._brownian import (BaseBrownian, BrownianInterval, BrownianPath, BrownianTree, ReverseBrownian,
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torchsde/_brownian/__init__.py", line 16, in <module>
    from .brownian_interval import BrownianInterval
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torchsde/_brownian/brownian_interval.py", line 21, in <module>
    import torch
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/__init__.py", line 524, in <module>
    from .functional import *
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/nn/functional.py", line 12, in <module>
    from .._jit_internal import boolean_dispatch, List, Optional, _overload, Tuple
  File "/home/conda/staged-recipes/build_artifacts/torchsde_1610279500117/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/torch/_jit_internal.py", line 27, in <module>
    from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by hmaarrfk** [comment]
I'm trying to patch this in: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/108

Otherwise, rebuilding is quite a bit of effort now.
