### ISSUE TITLE
`RuntimeError: MKL FFT error: Intel oneMKL DFTI ERROR: Inconsistent configuration parameters` with mkl-2024

### ISSUE THREAD

**Issue by mgorny** [conda-forge/pytorch-cpu-feedstock#301]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Looks like there's a problem with mkl-2024.2.2. Noticed it when trying to enable tests. Using the 

```pytb
$ PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=0 python test/test_ops_jit.py TestJitCPU.test_variant_consistency_jit_fft_fft2_cpu_complex64
E
======================================================================
ERROR: test_variant_consistency_jit_fft_fft2_cpu_complex64 (__main__.TestJitCPU.test_variant_consistency_jit_fft_fft2_cpu_complex64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/conda-bld/work_moved_libtorch-2.5.1-cpu_mkl_h5f89428_106_linux-64/test/test_ops_jit.py", line 109, in test_variant_consistency_jit
    self.indiv_variant_test_jit(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        device, dtype, op, sample, func_type, variant, has_fake_function
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/var/tmp/conda-bld/work_moved_libtorch-2.5.1-cpu_mkl_h5f89428_106_linux-64/test/test_ops_jit.py", line 156, in indiv_variant_test_jit
    check_against_reference(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<6 lines>...
        no_gradgrad=not op.supports_gradgrad,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_jit.py", line 108, in check_against_reference
    grads = torch.autograd.grad(allSum(outputs), recording_tensors,
                                allow_unused=allow_unused)
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/autograd/__init__.py", line 496, in grad
    result = _engine_run_backward(
        outputs,
    ...<5 lines>...
        accumulate_grad=False,
    )
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        t_outputs, *args, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )  # Calls into the C++ engine to run the backward pass
    ^
RuntimeError: MKL FFT error: Intel oneMKL DFTI ERROR: Inconsistent configuration parameters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_device_type.py", line 1140, in test_wrapper
    return test(*args, **kwargs)
  File "/var/tmp/conda-bld/work_moved_libtorch-2.5.1-cpu_mkl_h5f89428_106_linux-64/test/test_ops_jit.py", line 120, in test_variant_consistency_jit
    raise Exception(variant_error_info) from e  # noqa: TRY002
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: 
                 Error testing fft.fft2 function variant
                 with dtype: torch.complex64
                 with inputs SampleInput(input=tensor([[[ 0.4519-1.6687j, -1.3497+3.1941j, -8.9264-4.0518j,  3.6276-6.9550j,
   -8.5880-5.2066j, -2.2049-4.3718j,  6.0923-0.6148j],
  [ 0.8153-1.4545j, -5.3751+2.8520j, -2.8915-7.5140j,  0.1147+3.8840j,
   -7.9774-5.3941j, -4.7232+6.2016j, -7.0199-1.3300j],
  [ 0.6387-2.9121j,  4.9206-4.0014j,  6.7648-2.2684j, -4.0965-2.3907j,
    2.3617+8.0499j, -0.9205-1.8945j,  3.0848-3.1877j],
  [ 1.0688-2.7264j, -3.7338+2.4207j, -5.2879+7.2414j, -0.4194+2.7186j,
    1.6498-7.2553j, -5.6285+0.5283j,  6.1463+6.6689j],
  [ 4.5116+5.5040j, -4.5468+3.8238j,  2.0432-4.0802j,  7.7975+3.6276j,
   -3.9898+6.4498j, -2.0038-1.4510j, -5.5658-4.9406j],
  [ 0.9235-6.0854j,  7.3032-4.9497j,  3.0275+2.7930j, -7.1406+7.8375j,
   -2.5508+3.3611j, -7.5744-7.7703j,  3.0497+6.1885j]],

 [[ 2.7347+1.4139j, -5.8085-1.2180j,  2.9595+6.3969j, -3.0274+5.5602j,
   -4.6561-4.1872j,  6.7226-3.6585j, -5.0018+4.3699j],
  [-3.6242-3.0665j, -2.2476+7.2501j,  7.5155-6.1942j, -7.7748-8.6985j,
   -8.6626+5.4833j, -7.7189+6.7175j,  5.9785-0.3973j],
  [-1.6851-5.0840j,  4.2354+4.9089j,  4.1848-5.6581j,  3.4160+3.6999j,
    6.0055+5.5249j,  2.4432-0.0450j,  8.8184-4.5192j],
  [ 1.4375-8.2578j, -8.9884-5.9804j,  8.3846+0.4880j, -2.7509-3.0532j,
   -0.4755-1.3543j, -7.5389+2.9812j, -4.2917-0.3567j],
  [-1.4569+5.7937j,  1.2211-8.2981j,  8.7474-8.8791j,  5.8483+6.9294j,
   -4.9306-1.6164j,  3.1223+5.1523j,  7.7248-4.4619j],
  [ 7.0505+1.2090j, -4.5486+5.1965j,  8.9690-6.1245j, -4.6085-2.7860j,
   -4.8467-5.9044j,  4.2504-6.3633j, -3.9363+3.5810j]],

 [[ 1.4855+2.6930j, -1.9112+3.1822j, -1.2487+8.1739j,  0.1605+6.7395j,
    4.7378+5.3385j, -5.9193+4.2485j,  0.5862-1.5016j],
  [-6.4440+8.0353j,  2.8137-6.1565j, -6.3559+2.8448j, -2.9265+2.0644j,
    3.1701-8.6227j, -1.3536+7.4368j,  5.7509+7.1081j],
  [-1.3466+7.0001j, -2.8740+3.2901j, -3.5271-7.2450j, -2.2556-8.7708j,
   -8.8105+1.7250j, -0.5918+4.0027j,  7.7862-3.4462j],
  [ 5.5815+6.4713j, -6.9697+7.0167j,  8.0875-0.2620j, -3.6310+4.7267j,
    6.0261+4.6868j,  0.7755+0.4853j, -1.8758+4.8651j],
  [ 0.8443-4.4743j, -6.6609+2.1552j,  1.0760+8.3737j,  0.9953+8.9865j,
   -3.5583-6.3304j, -1.1792-3.2809j, -1.4970-2.7631j],
  [ 8.2300+3.9946j,  1.4586-0.1478j,  8.5900+3.9895j, -2.2568-8.6140j,
   -8.6059-3.3950j,  1.5673+1.5325j,  4.2586+4.0916j]],

 [[-3.8467+4.3392j,  4.9000+2.3846j,  7.2577-6.4897j,  1.4237-1.9427j,
    8.1282-7.0420j,  2.9550-6.4592j, -6.0499-8.1850j],
  [ 1.8745+8.2029j, -4.5403+0.6454j, -7.3490-6.4714j,  3.5490-1.2901j,
   -1.4631-5.0934j,  5.5921-6.8921j, -4.1412+5.8519j],
  [ 3.9626-8.2865j, -8.7425-5.2016j, -8.6528+6.3069j, -4.3739+3.5793j,
   -7.3106+2.2135j,  8.3889+5.8287j,  8.0646-1.9299j],
  [-1.2084-7.4524j, -3.8084-5.4723j, -0.3318+0.4794j, -2.2864-3.7192j,
    8.7766+1.1045j, -8.1575-3.2041j,  4.9697-8.4564j],
  [ 8.3740-0.9771j,  3.4598-2.1305j, -5.8572+4.8399j,  2.7278-4.8294j,
    3.6917-4.7133j, -6.6076-8.8687j,  6.6301+7.2904j],
  [ 6.2127+6.2237j,  8.2466+0.1138j, -8.3478-5.6941j,  5.3688-7.1158j,
   -1.1510-0.6876j, -0.2579-8.1676j,  7.4570-1.4829j]],

 [[-1.9497-3.2609j, -1.6071-1.4398j, -5.0406+7.4493j,  1.4543+1.0708j,
   -6.3619+8.9065j, -2.7798+5.7593j, -4.9274-1.1785j],
  [ 0.3750+0.5040j, -1.0892-2.0268j, -5.2186-2.7966j, -6.8724+6.9988j,
   -3.4293+0.1416j, -7.5392-6.6634j, -5.8855+3.4055j],
  [ 8.3858+0.0659j,  6.9550-8.3678j, -8.9337+3.4571j, -4.9290-4.6410j,
    7.1276-0.1551j,  5.7600-3.2788j,  1.0814+8.6245j],
  [ 0.7012+5.1418j,  8.0857+7.2150j,  7.5094-4.5757j,  3.3091-0.2827j,
   -4.1042-5.0177j,  3.9241+4.4959j,  0.9279+7.5567j],
  [ 2.9002+7.3141j,  4.6324-1.4293j, -3.2982-7.4901j,  8.9872-2.4968j,
    3.5917+5.0777j, -6.2488+4.3580j,  5.5003-4.6500j],
  [-3.4046+1.7749j,  7.6435+8.2865j, -1.8083-4.3086j,  4.2663-1.5021j,
    1.4435-7.2924j,  1.0314+2.2837j, -3.1866+1.4575j]]],
requires_grad=True), args=(), kwargs={'s': (3, 10), 'dim': (1, 2), 'norm': 'ortho'}, broadcasts_input=False, name=''):


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_utils.py", line 2979, in wrapper
    method(*args, **kwargs)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_device_type.py", line 448, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_device_type.py", line 1210, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_utils.py", line 1526, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "/home/mgorny/miniforge3/envs/pytorch/lib/python3.13/site-packages/torch/testing/_internal/common_device_type.py", line 1152, in test_wrapper
    raise e_tracked from e
Exception: Caused by sample input at index 0: SampleInput(input=Tensor[size=(5, 6, 7), device="cpu", dtype=torch.complex64], args=(), kwargs={'s': '(3,10)', 'dim': '(1,2)', 'norm': "'ortho'"}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
    PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=0 python test/test_ops_jit.py TestJitCPU.test_variant_consistency_jit_fft_fft2_cpu_complex64

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 0.068s

FAILED (errors=1)
```

I'm testing with different `mkl` versions now. Filing the bug mostly to have a paper trace.

### Installed packages

```shell
# packages in environment at /home/mgorny/miniforge3/envs/pytorch:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
attrs                     24.2.0             pyh71513ae_1    conda-forge
boto3                     1.35.76            pyhd8ed1ab_0    conda-forge
botocore                  1.35.76         pyge310_1234567_0    conda-forge
brotli-python             1.1.0           py313h46c70d0_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cffi                      1.17.1          py313hfab6e84_0    conda-forge
click                     8.1.7           unix_pyh707e725_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
cpython                   3.13.1          py313hd8ed1ab_102    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_1    conda-forge
execnet                   2.1.1              pyhd8ed1ab_1    conda-forge
expecttest                0.2.1              pyhd8ed1ab_1    conda-forge
filelock                  3.16.1             pyhd8ed1ab_1    conda-forge
fsspec                    2024.10.0          pyhd8ed1ab_1    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py313h11186cd_3    conda-forge
h2                        4.1.0              pyhd8ed1ab_1    conda-forge
hpack                     4.0.0              pyhd8ed1ab_1    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_1    conda-forge
hypothesis                6.122.1            pyha770c72_1    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_1    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_1    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libhwloc                  2.11.2          default_h0d58e46_1001    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
liblzma                   5.6.3                hb9d3cd8_1    conda-forge
libmpdec                  4.0.0                h4bc722e_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_1    conda-forge
libprotobuf               5.28.2               h5b01275_0    conda-forge
libsqlite                 3.47.2               hee588c1_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtorch                  2.5.1           cpu_mkl_h791ef64_106    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.49.2               hb9d3cd8_0    conda-forge
libxml2                   2.13.5               h0d44e9d_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
llvm-openmp               19.1.5               h024ca30_0    conda-forge
markupsafe                3.0.2           py313h8060acc_1    conda-forge
mkl                       2024.2.2            ha957f24_16    conda-forge
mpc                       1.3.1                h24ddda3_1    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
networkx                  3.4.2              pyh267e887_2    conda-forge
numpy                     2.2.0           py313hb30382a_0    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pip                       24.3.1             pyh145f28c_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_1    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
pytest                    8.3.4              pyhd8ed1ab_1    conda-forge
pytest-flakefinder        1.1.0              pyhd8ed1ab_0    conda-forge
pytest-rerunfailures      15.0               pyhd8ed1ab_1    conda-forge
pytest-xdist              3.6.1              pyhd8ed1ab_1    conda-forge
python                    3.13.1          ha99a958_102_cp313    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python_abi                3.13                    5_cp313    conda-forge
pytorch                   2.5.1           cpu_mkl_py313hf76930e_106    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s3transfer                0.10.4             pyhd8ed1ab_1    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
sleef                     3.7                  h1b44611_2    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sympy                     1.13.3           pyh2585a3b_104    conda-forge
tbb                       2021.13.0            hceb3a55_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.2.1              pyhd8ed1ab_1    conda-forge
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_1    conda-forge
zstandard                 0.23.0          py313h80202fe_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
active environment : pytorch
    active env location : /home/mgorny/miniforge3/envs/pytorch
            shell level : 4
       user config file : /home/mgorny/.condarc
 populated config files : /home/mgorny/miniforge3/.condarc
                          /home/mgorny/.condarc
          conda version : 24.11.0
    conda-build version : 24.11.2
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.11.0=0
                          __cuda=12.6=0
                          __glibc=2.40=0
                          __linux=6.12.3=0
                          __unix=0=0
       base environment : /home/mgorny/miniforge3  (writable)
      conda av data dir : /home/mgorny/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://mgorny.github.io/conda-channel/mgorny/linux-64
                          https://mgorny.github.io/conda-channel/mgorny/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mgorny/miniforge3/pkgs
                          /home/mgorny/.conda/pkgs
       envs directories : /home/mgorny/miniforge3/envs
                          /home/mgorny/.conda/envs
               platform : linux-64
             user-agent : conda/24.11.0 requests/2.32.3 CPython/3.12.7 Linux/6.12.3-gentoo-dist gentoo/2.17 glibc/2.40 solver/libmamba conda-libmamba-solver/24.11.1 libmambapy/2.0.4
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by h-vetinari** [comment]
I'm reopening this because we haven't actually solved the issue, just avoided it by pinning to `mkl <2024`

**Comment by h-vetinari** [comment]
@mgorny, there's now an upstream PR for the issue you raised. Might be worth backporting this into #309 directly

**Comment by mgorny** [comment]
Working on it, thanks for letting me know! I wish GitHub would notify me when someone opens a pull request for my issue.

**Comment by mgorny** [comment]
I've tested it and confirmed it to solve the issue I was seeing. I have a commit to remove the pin and add the patch ready. However, I won't push it before the current CI job finishes.
